name: Kube Security Check

on: [push]

jobs:
  kubeaudit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install kubeaudit
        run: |
          curl -sSL https://github.com/Shopify/kubeaudit/releases/latest/download/kubeaudit-linux-amd64 -o kubeaudit
          chmod +x kubeaudit
          sudo mv kubeaudit /usr/local/bin/
      - name: Run kubeaudit
        run: kubeaudit all

